GeminiApi:
  ApiKey: root
  BaseUrl: root
nutriemother:
  filepaths:
    surveyImageUploadPath: demo
    ashaImageUploadPath: demo
aws:
  accessKey: demo	
  secretKey: demo
  s3:
    region: demo
jwt:
  key: jwt
  subject: subject
  issuer: issuer
  audience: audience
spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true